In [1]:
import numpy as np
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [2]:
b = np.reshape(a,(2,3*4))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [3]:
f = a.shape
np.prod(f[1:])

12

In [4]:
L = 3
for cnt in range(L-1,0,-1):
    print(cnt)

2
1


In [5]:
x = np.array([[1,2,3],[11,22,23]])
print(x)
print()

gamma = np.array([1,2,3])
print(gamma)
print()

print(x*gamma)

[[ 1  2  3]
 [11 22 23]]

[1 2 3]

[[ 1  4  9]
 [11 44 69]]


In [6]:
pad = 1
x  = np.array([[1,2,3],[11,22,23]])
x2 = np.pad(x,((pad,pad),(pad,pad)),'constant', constant_values=(0,0))
x2

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  0],
       [ 0, 11, 22, 23,  0],
       [ 0,  0,  0,  0,  0]])

In [7]:
x_shape = (3,2,2)
x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
print(x)
print()

x2 = np.pad(x,((0,0),(1,1),(1,1)),'constant', constant_values=(0,0))
print(x2)

[[[-0.1        -0.04545455]
  [ 0.00909091  0.06363636]]

 [[ 0.11818182  0.17272727]
  [ 0.22727273  0.28181818]]

 [[ 0.33636364  0.39090909]
  [ 0.44545455  0.5       ]]]

[[[ 0.          0.          0.          0.        ]
  [ 0.         -0.1        -0.04545455  0.        ]
  [ 0.          0.00909091  0.06363636  0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.11818182  0.17272727  0.        ]
  [ 0.          0.22727273  0.28181818  0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.33636364  0.39090909  0.        ]
  [ 0.          0.44545455  0.5         0.        ]
  [ 0.          0.          0.          0.        ]]]


In [8]:
15.3 % 1

0.3000000000000007

In [9]:
x = np.array([[111,12],[10,1]])
print(x)

print(np.argmax(x))

y = np.zeros((2,2))
z = np.ravel(y)
z[2] = -4
z = z.reshape(y.shape)
print(z)

[[111  12]
 [ 10   1]]
0
[[ 0.  0.]
 [-4.  0.]]


In [10]:
a = (1,2,3)
b = (0,1,1)
c = a+b
print(c)
d = [sum(x) for x in zip(a,b)]
print(d)

(1, 2, 3, 0, 1, 1)
[1, 3, 4]


In [11]:
x_shape = (3,2,2)
x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
print(x)
print()

z = x.reshape((3,4))
print(z)

x[np.ix_([1],np.arange(2),np.arange(2))] = np.zeros((2,2))
print(x)

[[[-0.1        -0.04545455]
  [ 0.00909091  0.06363636]]

 [[ 0.11818182  0.17272727]
  [ 0.22727273  0.28181818]]

 [[ 0.33636364  0.39090909]
  [ 0.44545455  0.5       ]]]

[[-0.1        -0.04545455  0.00909091  0.06363636]
 [ 0.11818182  0.17272727  0.22727273  0.28181818]
 [ 0.33636364  0.39090909  0.44545455  0.5       ]]
[[[-0.1        -0.04545455]
  [ 0.00909091  0.06363636]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.33636364  0.39090909]
  [ 0.44545455  0.5       ]]]


In [16]:
x = np.arange(9)
x = x.reshape((3,3,1,1))
print(x.shape)
x = np.squeeze(x)
print(x.shape)

(3, 3, 1, 1)
(3, 3)


In [19]:
x_shape = (3,2,4,5)
x = np.linspace(-0.1, 0.5, num=np.prod(x_shape)).reshape(x_shape)
print(x)
print()

[[[[-0.1        -0.09495798 -0.08991597 -0.08487395 -0.07983193]
   [-0.07478992 -0.0697479  -0.06470588 -0.05966387 -0.05462185]
   [-0.04957983 -0.04453782 -0.0394958  -0.03445378 -0.02941176]
   [-0.02436975 -0.01932773 -0.01428571 -0.0092437  -0.00420168]]

  [[ 0.00084034  0.00588235  0.01092437  0.01596639  0.0210084 ]
   [ 0.02605042  0.03109244  0.03613445  0.04117647  0.04621849]
   [ 0.0512605   0.05630252  0.06134454  0.06638655  0.07142857]
   [ 0.07647059  0.08151261  0.08655462  0.09159664  0.09663866]]]


 [[[ 0.10168067  0.10672269  0.11176471  0.11680672  0.12184874]
   [ 0.12689076  0.13193277  0.13697479  0.14201681  0.14705882]
   [ 0.15210084  0.15714286  0.16218487  0.16722689  0.17226891]
   [ 0.17731092  0.18235294  0.18739496  0.19243697  0.19747899]]

  [[ 0.20252101  0.20756303  0.21260504  0.21764706  0.22268908]
   [ 0.22773109  0.23277311  0.23781513  0.24285714  0.24789916]
   [ 0.25294118  0.25798319  0.26302521  0.26806723  0.27310924]
   [ 0.27815126  